modLoader="javafml"
loaderVersion="[28,)"
[[mods]] #mandatory
modId="equivalency"
version="${file.jarVersion}"
displayName="Equivalency"
authors="OrionOnline, LDTTeam"
description='''
Minecraft mod spiritually based on Equivalent Exchange 2 and 3, as well as Thaumcraft and Botania. This mod allows you to exchange blocks, items, power and other gameplay components based on their internal biological components.
'''
